sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk7

notifications:
  irc:
    channels:
      - "chat.freenode.net#vectorgraphics2d"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
